version: '3.8'
services:
  nifi:
    image: apache/nifi:2.1.0 
    ports:
      - "8443:8443"
    environment:
      # HTTPS Configuration
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_SECURITY_KEYSTORE=/opt/nifi/nifi-current/security/keystore.jks
      - NIFI_SECURITY_KEYSTORE_TYPE=JKS
      - NIFI_SECURITY_KEYSTORE_PASSWD=keystorePassword
      - NIFI_SECURITY_KEY_PASSWD=keyPassword
      
      # Single-User Auth (QUOTED VALUES)
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=single-user-provider
      - NIFI_SECURITY_USER_SINGLE_USER_CREDENTIALS_USERNAME="admin"
      - NIFI_SECURITY_USER_SINGLE_USER_CREDENTIALS_PASSWORD="adminPassword123!" 
      - NIFI_SENSITIVE_PROPS_KEY="mySuperSecretKey123!"  
      
      # Performance
      - NIFI_JVM_HEAP_MAX=4g
    volumes:
      - ./security:/opt/nifi/nifi-current/security
      - ./data:/opt/nifi/nifi-current/data
    networks:
      - nifi-net

networks:
  nifi-net:
    driver: bridge