version: "3.8"
services:
  nifi:
    container_name: nifi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_PROXY_HOST=192.168.17.184 # Need to add the server ip
      - NIFI_SECURITY_KEYSTORE=/opt/nifi/nifi-current/security/keystore.jks
      - NIFI_SECURITY_KEYSTORE_TYPE=JKS
      - NIFI_SECURITY_KEYSTORE_PASSWD=keystorePassword
      - NIFI_SECURITY_KEY_PASSWD=keyPassword
      - NIFI_SECURITY_TRUSTSTORE=/opt/nifi/nifi-current/security/truststore.jks
      - NIFI_SECURITY_TRUSTSTORE_TYPE=JKS
      - NIFI_SECURITY_TRUSTSTORE_PASSWD=truststorePassword
      - NIFI_SENSITIVE_PROPS_KEY=mySuperSecretKey123!
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_CLUSTER_NODE_ADDRESS=nifi
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_JVM_HEAP_INIT=2g
      - NIFI_JVM_HEAP_MAX=4g
      - NIFI_WEB_HTTP_HOST=nifi
      - NIFI_WEB_PROXY_HOST=nifi:8443
      - NIFI_FLOWFILE_REPOSITORY_ALWAYS_SYNC=false
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=adminPassword123!
    volumes:
      - ./security:/opt/nifi/nifi-current/security
      - ./data:/opt/nifi/nifi-current/data
    networks:
      - nifi-net
    extra_hosts:
      - "nifi:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/nifi-api/system-diagnostics"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  nifi-net:
    driver: bridge
